root: true
parser: 'babel-eslint'
parserOptions:
  sourceType: 'module'
env:
  browser: true,
  node: true,
  es6: true,
plugins: ['html']
globals:
  window: true,
  $: true,
  focus_domain: true,
  UE: true,
rules:
  array-bracket-spacing: [2, "never"] # 数组中括号前后不允许空格
  arrow-body-style: [2] #直接返回省略return
  indent: [2, 2, {"SwitchCase": 1}] # 两格缩进
  quotes: [2, "single"] # 单引号

  brace-style: [2, "1tbs"] # 大括号风格
  #comma-dangle: [2, "never"] # 禁用拖尾逗号
  computed-property-spacing: [2, "never"] # 禁止在计算属性中使用空格
  eqeqeq: [1]  #===
  no-multiple-empty-lines: [2, {"max": 1}] # 禁止多行空行
  no-bitwise: [2] # 禁止按位运算符
  no-tabs: [2] # 不能使用tab
  # no-cond-assign: [2, 'always'] # 判断语句无赋值语句
  no-dupe-keys: [2] # 对象无重复键名
  no-dupe-args: [2] # 参数名无重复
  no-redeclare: [2] # 禁止多次声明同一变量
  no-unused-vars: [1, {"vars": "local", "args": "none", "caughtErrors": "none"}] # 禁止未使用过的变量
  no-const-assign: [2] #禁止修改const声明的变量
  no-trailing-spaces: [1] #一行结束后面不要有空格
  no-undef: [2]
  no-else-return: [2]
  no-with: [2]
  no-array-constructor: [2] #禁止使用数组构造器
  no-caller: [1] #禁止使用arguments.caller或arguments.callee
  no-duplicate-case: [2] #switch中的case标签不能重复
  no-empty: [2] #块语句中的内容不能为空
  no-constant-condition: [2] #禁止在条件中使用常量表达式 if(true) if(1)
  no-empty-character-class: [2] #正则表达式中的[]内容不能为空
  no-eq-null: [2] #禁止对null使用==或!=运算符
  no-ex-assign: [2] #禁止给catch语句中的异常参数赋值
  no-extend-native: [2] #禁止扩展native对象
  no-extra-semi: [2] #禁止多余的冒号
  no-extra-parens: [2] #禁止非必要的括号
  no-fallthrough: [1] #禁止switch穿透
  no-new-func: [1] #禁止使用new Function
  no-octal: [2] #禁止使用八进制数字
  no-floating-decimal: [2] #禁止省略浮点数中的0 .5 3.
  no-lone-blocks: [2] #禁止不必要的嵌套块
  no-nested-ternary: [2] #禁止使用嵌套的三目运算
  no-new-wrappers: [2] #禁止使用new创建包装实例，new String new Boolean new Number
  no-return-assign: [2] #return 语句中不能有赋值表达式
  no-self-compare: [2] # 不能比较自身
  no-sparse-arrays: [2] #禁止稀疏数组， [1,,2]
  no-undef-init: [2] #变量初始化时不能直接给它赋值为undefined
  object-curly-spacing: [2, "always"] # 花括号前后必须空格
  key-spacing: [2, {"beforeColon": false, "afterColon": true, "mode": "strict"}] # {a: 1} 冒号与键无空格，与值有一个空格
  keyword-spacing: [2, {"before": true, "after": true}] # 关键词前后必须加空格
  prefer-const: [2] #用const
  prefer-destructuring: [2, { "array": false, "object": true}]  #用对象解构
  space-before-blocks: [2, "always"] # 强制{}之前加空格
  space-before-function-paren: [2, "always"] # function () function与() 之间加空格
  space-in-parens: [2, "never"] # 圆括号前后不加空格
  space-unary-ops: [2, {"words": true, "nonwords": true, "overrides": {"!": false, ".": false}}] # 一元操作符前后必须加空格
  semi: [1, "always"] # 句末不加分号
